### ISSUE TITLE
Web page title should be better

### ISSUE THREAD

**Issue by mivade** [pennmem/brain_viz_unity#1]
"brain_viz_unity" is not great. It should be something more like "Brain Visualization - R1337E".

It would also be nice to use the favicon we are using for the rest of the web app (although this might be something we can add by default for anything served from the web app).

**Comment by milkshakeiii** [comment]
Web page title will now be "Brain Visualization."  Still looking into how to update it in order to make it change per subject.

**Comment by mivade** [comment]
Good enough for now.
